import {
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLeetcode,
  IconBrandLinkedin,
  IconBrandTwitter,
  IconBrandYoutube,
} from "@tabler/icons-react";
const Info = {
  name: "Chirag Gupta",
  stack: [
    "Freelancer",
    "Software Engineer",
    "Full Stack Developer",
    "Frontend Developer",
    "Open Source Contributor",
  ],
  bio: "I'm a passionate software engineer specialized in crafting efficient and scalable solutions, deliver top-notch web applications, and provide freelance services that exceed client expectations. Let's connect and create something amazing together!",
};

const ProjectInfo = [
  {
    title: "Digiwhistle - Influencer Management ERP",
    desc: [
      "Developed a modern, fully responsive Influencer Management ERP platform, Digiwhistle, enabling seamless management of influencer profiles, brand campaigns, and employee operations across all devices.",
      "Implemented secure user authentication and granular role management using Next.js middleware, cookies, and Redux Toolkit.",
      "Integrated with social media platforms via APIs to fetch and manage influencer statistics, ensuring real-time data accuracy.",
      "Facilitated brand campaign creation and management, including collaboration with multiple influencers, tracking deliverables, and analyzing brand engagement metrics.",
      "Streamlined payroll, invoicing, and commission processes through seamless integration with Zoho Books and Razorpay APIs.",
    ],
    image: "digiwhistle.png",
    live: true,
    technologies: [
      "NextJs",
      "NodeJs",
      "Postgres SQL",
      "Typescript",
      "Tailwind",
      "Redux Toolkit",
      "ShadCN",
      "Type ORM",
      "Docker",
      "Digital Ocean",
    ],
    link: "https://landing-page-frontend-sigma.vercel.app/",
    github: "https://github.com/DigiWhistle/landing-page-frontend",
  },
  {
    title: "Facebook Clone",
    desc: [
      "Facebook Clone is a full-stack web application that replicates the core features of Facebook, including user authentication, posting, and commenting. The front end is built with React, TailwinCSS, Tabler-Icons, Mantine and Firebase, while the back end uses Firebase for user authentication and data storage. Users can create an account, log in, post updates, and comment on posts. The app features real-time updates, so users can see new comments as they are posted. Facebook Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
    ],
    image: "Facebook.png",
    live: false,
    technologies: [
      "React",
      "Springboot",
      "MongoDB",
      "Tailwind",
      "Tabler-Icons",
      "Firebase",
    ],
    link: "https://github.com/Code-Mars/Facebook-Clone",
    github: "https://github.com/Code-Mars/Facebook-Clone",
  },
  {
    title: "Spotify Clone",
    desc: [
      "Spotify Clone is a full-stack web application that replicates the core features of Spotify, including user authentication, music playback, and playlist creation. The front end is built with React, TailwindCSS, Heroicons, and Firebase, while the back end uses Firebase for user authentication and data storage. Users can create an account, log in, search for songs, and create playlists. The app features real-time updates, so users can see new songs as they are added. Spotify Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
    ],
    image: "Spotify.png",
    live: false,
    technologies: [
      "React",
      "Springboot",
      "Tailwind",
      "Tabler-Icons",
      "MongoDB",
      "Firebase",
    ],
    link: "https://github.com/Code-Mars/Spotify-Clone",
    github: "https://github.com/Code-Mars/Spotify-Clone",
  },
  {
    title: "Travel Tracker",
    desc: [
      "Travel Tracker is a full-stack web application that allows users to track their travel experiences and share them with others. The front end is built with React, Bootstrap, while the back end uses Node.js, Express, and PostgresSQL. Users can create an account, log in, add new trips, and view their past trips on a map. The app features a clean, modern design with interactive maps and a user-friendly interface. Travel Tracker combines functionality with style, making it easy and enjoyable to record and share travel memories.",
    ],
    image: "Travel.png",
    live: false,
    technologies: ["React", "Node.js", "PostgresSQL", "Express", "Bootstrap"],
    link: "https://github.com/Code-Mars/Travel-Tracker",
    github: "https://github.com/Code-Mars/Travel-Tracker",
  },
  {
    title: "Instagram Clone",
    desc: [
      "Instagram Clone is a full-stack web application that replicates the core features of Instagram, including user authentication, image uploading, and commenting. The front end is built with React, TailwindCSS, and Heroicons, while the back end uses Firebase for user authentication and image storage. Users can create an account, log in, upload images, and comment on posts. The app features real-time updates, so users can see new comments as they are posted. Instagram Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
    ],
    image: "Instagram.png",
    live: false,
    technologies: [
      "React",
      "Springboot",
      "Tailwind",
      "Heroicons",
      "Firebase",
      "MongoDB",
    ],
    link: "https://github.com/Code-Mars/Instagram-Clone",
    github: "https://github.com/Code-Mars/Instagram-Clone",
  },
  {
    title: "CodeX Code Editor",
    desc: [
      "CodeX is a modern, fully responsive code editor built using React, TailwindCSS, and Ace Editor, offering a seamless coding experience across all devices. It features syntax highlighting for popular programming languages, including HTML, CSS, JavaScript, Python, and Java. Users can create, edit, and save code files, with the option to download them as text files. CodeX combines robust functionality with a sleek, intuitive design, making coding effortless and enjoyable.",
    ],
    image: "CodeX.png",
    live: false,
    technologies: ["React", "Tailwind", "Ace Editor"],
    link: "https://github.com/Code-Mars/CodeX",
    github: "https://github.com/Code-Mars/CodeX",
  },
];

const SkillInfo = [
  {
    title: "Frontend",
    skills: [
      "HTML",
      "CSS",
      "SASS",
      "JavaScript",
      "React JS",
      "Next JS",
      "Tailwind CSS",
      "Vue",
      "Redux",
      "Recharts",
      "Material UI",
      "Jest",
      "Babel",
      "Webpack",
      "Three JS",
      // "Angular",
      // "Bootstrap",
    ],
  },
  {
    title: "Backend",
    skills: [
      // "Springboot",
      "Node JS",
      "Express JS",
      "Fast API",
      "MongoDB",
      "PostgresSQL",
      "Chroma DB",
      "Firebase",
    ],
  },
  {
    title: "Languages",
    skills: ["C", "C++", "JavaScript", "TypeScript", "Python"],
  },
  {
    title: "Tools",
    skills: [
      "Git",
      "Github",
      "VS Code",
      "Figma",
      "Docker",
      "Postman",
      "MongoDB Compass",
      // "Spring Tool Suite",
    ],
  },
];
const socialLinks = [
  { link: "https://github.com/ChiragG2101", icon: IconBrandGithub },
  {
    link: "https://www.linkedin.com/in/chirag-gupta-2101/",
    icon: IconBrandLinkedin,
  },
  { link: "https://www.instagram.com/chiragg_2101/", icon: IconBrandInstagram },
  { link: "https://x.com/Chirag_2101", icon: IconBrandTwitter },
  //   {
  //     link: "https://www.youtube.com/channel/UC1ki6jaFvFiH_E79b9FYptw",
  //     icon: IconBrandYoutube,
  //   },
  //   { link: "https://www.leetcode.com/u/CodeMars", icon: IconBrandLeetcode },
];

const ExperienceInfo = [
  {
    role: "Software Developer - Founder's Office",
    company: "Adaapt AI (formerly Terobots )",
    image: "adaapt.png",
    date: "Jan 2024 - Present",
    desc: [
      " Built complete auth & role management module on frontend by utilizing Higher order components, nextjs middleware, cookies & redux toolkit ",
      " Carried out a revamp of Platform’s Frontend by applying React Server Components, Error/Loading States Management, Caching & Memoization, Animations & dev best practices",
    ],
    skills: [
      "Next JS",
      "Typescript",
      "Tailwind CSS",
      "Redux Toolkit",
      "Node JS",
      "Express JS",
      "MongoDB",
      "Microservices",
    ],
  },
  {
    role: "Software Developer Intern",
    company: "Adaapt AI (formerly Terobots )",
    image: "adaapt.png",
    date: "June 2023 - Dec 2023",
    desc: [
      "Developed analytics dashboards for bot performance at various hierarchy levels and created a global filter component & hook",
      "Built REST API endpoints for Automation Bot data analytics and insights.",
      // "Developed an end-to-end LinkedIn Automation microservice using Python FastAPI framework, MongoDB, and relevant libraries",
    ],
    skills: [
      "Next JS",
      "Typescript",
      "Tailwind CSS",
      "Recoil",
      "Chart.js",
      "Node JS",
      "Express JS",
      "MongoDB",
      "Microservices",
    ],
  },
  {
    role: "Frontend Developer Intern",
    company: "Finlight",
    image: "finlight.png",
    date: "Sept 2022 - Feb 2023",
    desc: [
      "Developed a dynamic, user-friendly & mobile-responsive Finlight community webpage, which garnered over 2000+ members on launch day",
      "Designed and implemented the coupon system in the admin panel, connecting it with frontend using REST APIs",
    ],
    skills: [
      "React.js",
      "Next.js",
      "Redux",
      "Tailwind CSS",
      "Material UI(MUI)",
      "Node.js",
    ],
  },
];
const Slugs = [
  "typescript",
  "spring",
  "javascript",
  "dart",
  "java",
  "react",
  "angular",
  "flutter",
  "android",
  "html5",
  "css3",
  "springboot",
  "mongodb",
  "selenium",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "mysql",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
];
export { Info, ProjectInfo, socialLinks, SkillInfo, ExperienceInfo, Slugs };
